"""Functions handling API endpoints."""

import database
import models_autogenerated as models

def search():
    """Get all users from the database"""
    users = models.User.query.filter_by()
    user_dicts = map(lambda user: user.to_dict(), users)
    return list(user_dicts)
